# Generated by Django 3.0.6 on 2020-05-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.TextField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('hostname', models.TextField(blank=True, db_column='Hostname', null=True)),
                ('last_known_location', models.TextField(blank=True, db_column='Last Known Location', null=True)),
                ('ipv4', models.TextField(blank=True, db_column='IPv4', null=True)),
                ('ipv6', models.TextField(blank=True, db_column='IPv6', null=True)),
                ('operating_system', models.TextField(blank=True, db_column='Operating System', null=True)),
                ('physical_virtual_machine', models.TextField(blank=True, db_column='Physical/Virtual Machine', null=True)),
                ('owner', models.TextField(blank=True, db_column='Owner', null=True)),
                ('administrator', models.TextField(blank=True, db_column='Administrator', null=True)),
                ('u_of_a_tag_number', models.TextField(blank=True, db_column='U of A Tag Number', null=True)),
                ('make_model', models.TextField(blank=True, db_column='Make/Model', null=True)),
                ('processor', models.TextField(blank=True, db_column='Processor', null=True)),
                ('ram_gb_field', models.TextField(blank=True, db_column='RAM (GB)', null=True)),
                ('storage_space_gb_field', models.TextField(blank=True, db_column='Storage Space (GB)', null=True)),
                ('gpu', models.TextField(blank=True, db_column='GPU', null=True)),
                ('serial_number', models.TextField(blank=True, db_column='Serial Number', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('rack_number', models.TextField(blank=True, db_column='Rack Number', null=True)),
                ('srit_access', models.TextField(blank=True, db_column='SRIT Access', null=True)),
                ('power_up', models.TextField(blank=True, db_column='Power Up', null=True)),
                ('support_team', models.TextField(blank=True, db_column='Support Team', null=True)),
                ('department', models.TextField(blank=True, db_column='Department', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
            options={
                'db_table': 'machines',
                'managed': False,
            },
        ),
    ]
