# Generated by Django 3.0.6 on 2020-05-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machines',
            options={'managed': False, 'verbose_name_plural': 'machines'},
        ),
    ]
